[[redirects]]
  from = "/api"
  to = "https://zozcode.cleverapps.io/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"